image: python:3.5.1

pipelines:
  default:
    - step:
        script:
          - pip install -r test_require.txt
          - py.test --cov-report term --doctest-modules --cov=changetext.py changetext.py test_changetext.py
