from typing import Union, Optional, overload, Callable


def any_in_tag(gram: Union[set, str], parse) -> bool: ...
def inflect_noun(word: str, case: str, orig_form: Union[str, set, None]=None) -> Optional[str]: ...

def utf16_codec(func: Callable) -> Callable: ...

@overload
def ChangeText(text: bytes) -> Optional[bytes]: ...
@overload
def ChangeText(text: str) -> Optional[str]: ...

def init() -> None: ...
