[tool.poetry]
name = "changetext"
version = "0.1.0"
description = ""
authors = ["insolor <insolor@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pymorphy2 = "^0.9.1"

[tool.poetry.group.dev.dependencies]
flake8 = "^5.0.4"
pytest = "^8.0.2"
pytest-cov = "^4.1.0"
black = "^24.3.0"
isort = "^5.13.2"
ruff = "^0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 120
select = ["E", "F", "UP"]
ignore = ["UP015"]
unfixable = ["F401"]
target-version = "py38"
